header:
- user-agent: Mozilla/5.0 (Linux; Android 13; Mi 10 Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.100 Mobile Safari/537.36 ZhilinEai/3.3 ZhilinNuaaApp AgentWeb/5.0.0  UCBrowser/11.6.4.950
  referer: https://ehall3.nuaa.edu.cn/v2/reserve/m_reserveDetail?id=17
  Cookie: eai-sess=hi1tputvtogm04qsbgh62d6hd0; UUkey=669cb704a2ec564bce00e8708e0a6bd6; PHPSESSID=cpjucolgvefond3n3u263r4fc0; vjvd=c95d07e3a8ee74d3c1570152cfa2675a; vjuid=352722; ioGBNZZUiF6NS=5TvGa8f1aWcG9DTPhVlVdfTcF6NOELSyAQFarhi_pctEc8yrD0Ywo1bHnuBQovzBvH_p505verdp5PfZBKxCBPq; vt=258468553; ioGBNZZUiF6NT=5R5q4TbIGi5lqqqDYa5vV6G3umNhe_A_hgQmwzk6ibCidNsetm.IZT3uVVsT6.k0PTRZlxF9__UzGwsrecRDiWDugxuVMsvu2v8_5VWoo7P1bgEMj8l7SWZJOust250wUwH3p3mTAGwz_xEK_rBpHCYwNLknGJPW5pCi_HoMTegsDr7nAB0KYxlg2J7e8GfQUavDdQPvZigitT7cW8WSzewe10azNnu8WmjMOZRcrfpaL3hVySTe.r6CLVfcm87lbHERZUP58NmadYZDYHl4YFLn9hKkl8yL1_vHGw83DEoMe8wJQJSmbC8XMLtqaI4ZWdMLlnwNgl03KG1V3kwmG79UrC4WOt3vsnWeQL2_W5NoL7qTx.UpWjlCHIxhrVCdQg
- user-agent: Mozilla/5.0 (Linux; Android 13; Mi 10 Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.100 Mobile Safari/537.36 ZhilinEai/3.3 ZhilinNuaaApp AgentWeb/5.0.0  UCBrowser/11.6.4.950
  referer: https://ehall3.nuaa.edu.cn/v2/reserve/m_reserveDetail?id=17
  Cookie: eai-sess=appkgsur2qa83685887r1n69h4; ioGBNZZUiF6NS=5VAYNdM.aJS8bmOtNhuqaaSeaheubbioG3OG8k9FnkgqzQKyTyoDBkdSAf56OJmZAU7Tqy71z46cg9H0ZYNRxsq; UUkey=608c53cb5dac7300792257bfc279e014; PHPSESSID=7lapk6plel3jmdq8d2nd28lra4; vjvd=25724049877a0a9fbae11689fcf5ac80; vjuid=352668; vt=258554093; ioGBNZZUiF6NT=5R5DxuKIfPwQqqqDYnAxYkqg.45Wq8l79IB0NLVn.Ilpq5mRyJKj9.bYqQm1Vt2HZ1zzuYKyhBdoA_9A6IIwr_MD4Ic6NKtvgWTBmMzV4sod_6CwcOcHCl3yvLypDSd1HqTScuZdVrQ8S5gXLTbDVGL6axN5nTwFqJ_DACrbEmP33UqOHUA8Un5Fw4fhqU5V3L6YOMtdZzSnQ6I7Wc3yeX3mJZSGzsXPOzd.J4zFUUS2VE9Fi8nVYTsv7CqBEAgYlmssgA9C4Bn9BsKFkZPBnv4tFzS3sljCbwXlEQ.MaivuETE4fTyHUY3fjJmmF4v9hAWqrODoow.JwrcAX8c1C.6xu6qoMtlL38AAkPUx03NbW7ZfB8sHchJvPn0FH_.a8Q
reservation:
  resource_id: 17
  data: 
  - date: "2025-01-11"
    period: 9355
    sub_resource_id: 28140
  - date: "2025-01-11"
    period: 9356
    sub_resource_id: 28141
captcha:
  username: "18056639636"
  password: "mao123456"
  usertoken: oB+QxJZNhoAvj3KnPevU5fRv1R/0satKpywR7fPsKqVI2/P1EUNiOTWEuVBr+Vjx6JZLztB9fon61lJ2h8sdGA==
  ID: "31989659"
  version: 3.1.1
schedule:
  use: yes
  day: null
  time: "07:00:02"
retry: yes
max-tries: 3

